highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems:
  - jekyll-sitemap
permalink: blogs/:title/
title: Tamanna Goyal
email: tamannagoyal0003@gmail.com
description: Website of Tamanna Goyal, Undergraduate student at Amity University
keywords: Tamanna, Goyal, tamc0de,  security, developer, geek, programmer, github
baseurl: ""
url: https://tamec0de.com
name: Tam Code\'s blog
author:
  name: Tamanna Goyal
  email: tamannagoya0003@gmail.com
